version: 2
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
