[workspace]
resolver = "3"
members = [
    "qitech_lib_common",
    "qitech_lib_ethercat_hal",
    "qitech_lib_ethercat_hal_derive",
    "qitech_lib_units",
    "qitech_lib_xtrem",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0-only"

[workspace.dependencies]
# Workspace crates
qitech_lib_common = { path = "qitech_lib_common" }
qitech_lib_ethercat_hal = { path = "qitech_lib_ethercat_hal" }
qitech_lib_ethercat_hal_derive = { path = "qitech_lib_ethercat_hal_derive" }
qitech_lib_units = { path = "qitech_lib_units" }
qitech_lib_xtrem = { path = "qitech_lib_xtrem" }

# External crates
anyhow = "1.0.102"
bitvec = "1.0.1"
core_affinity = "0.8.3"
libc = "0.2.186"
tokio = "1.50.0"

[package]
name = "qitech_lib"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitvec.workspace = true
qitech_lib_common.workspace = true
qitech_lib_ethercat_hal.workspace = true
qitech_lib_ethercat_hal_derive.workspace = true
qitech_lib_units.workspace = true
qitech_lib_xtrem.workspace = true
tokio.workspace = true

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.0", features = ["alloc"] }
core_affinity.workspace = true

[lib]

[features]
# This defines 'mock' at the root level and passes it to 'qitech_lib_ethercat_hal'
mock = ["qitech_lib_ethercat_hal/mock"]
