[package]
name = "ethercat"
version = "6.7.0"
edition = "2024"
description = "A subcrate within my workspace"

[dependencies]
# Adding ethercrab from GitHub as requested
ethercrab = { git = "https://github.com/qitechgmbh/ethercrab" }
ta = "0.5.0"
tokio = { version = "1.49.0", features = ["rt", "macros","rt-multi-thread","time"] }

[lib]
