[package]
name        = "xtrem"
version     = "0.1.0"
edition.workspace = true
description = "GRAM XTREM / XTREM-S weighing module communication protocol (UDP)"

[dependencies]
tokio = { workspace = true, features = ["sync","rt-multi-thread","macros","net","time"] }
anyhow.workspace = true
common.workspace = true
units.workspace = true

[lib]
